- .eslintrc.json
- .prettierrc.json
- package-lock.json
- package.json
- src/app/components/buttons/ActionButton.tsx
- src/app/components/buttons/ButtonDisplay.tsx
- src/app/components/buttons/MyPrimary.tsx
- src/app/components/buttons/MyPrimaryFull.tsx
- src/app/components/buttons/MyPrimaryFullDisabled.tsx
- src/app/components/buttons/MySecondary.tsx
- src/app/components/buttons/MySecondaryFull.tsx
- src/app/components/buttons/MyTertiary.tsx
- src/app/components/buttons/MyTertiaryFull.tsx
- src/app/components/buttons/button.module.css
- src/app/layout.tsx
- src/app/page.tsx
> Adding Eslint and Prettier and fixing linting issues

- src/app/page.tsx
Adding google tag for Neurostudy portal.
> Adding GTag

- src/app/components/footer/Footer.tsx
- src/app/components/navbar/Navbar.tsx
- src/app/services/coaching/page.module.css
- src/app/services/coaching/page.tsx
- src/app/services/networking/page.module.css
- src/app/services/networking/page.tsx
- src/app/services/neurodiversitytraining/page.module.css
- src/app/services/neurodiversitytraining/page.tsx
- src/app/services/workshops/page.module.css
- src/app/services/workshops/page.tsx
Create services pages:
1. neurodiversity training
2. workshops
3. networking
> Create service pages

- src/app/components/popupSubscribe/dialog.module.css
- src/app/components/textbox/textbox.module.css
1. fixed subscription mobile resolution by taking into account mobile width <= 320px.
> Fixed subscription mobile resolution

- src/app/articles/article/page.tsx
- src/app/blogs/blog/page.tsx
- src/app/components/article/Article.tsx
- src/app/components/article/article.module.css
- src/app/components/blog/Blog.tsx
- src/app/components/blog/blog.module.css
- src/app/components/popupSubscribe/DialogComponent.tsx
- src/app/components/popupSubscribe/dialog.module.css
- src/app/components/textbox/textbox.module.css
- src/app/globals.css
1. fixed articles and blog card descriptions overflow
2. fixed subscription pop up modal on mobile(width<=320px) small resolution
3. took care of scenario where no podcast is available
> Fixed css and podcast

- src/app/components/navbar/Navbar.tsx
- src/app/components/navbar/navbar.module.css
- src/app/components/popupSubscribe/dialog.module.css
1. fixed hamburger dropdown of navbar on mobile dimension as it had missing categories (career coaching and placements).
> Fixed navbar dropdown on mobile

- src/app/page.tsx
Inserting scripts only in production environment.
> Collecting google analytics only for production

- src/app/about/page.tsx
- src/app/neurodivergentmates/page.tsx
- src/app/page.tsx
- Add jpgs to meta images instead of svg
> Fixing meta images

- src/app/components/auth/Login.tsx
- src/app/components/buttons/MyPrimary.tsx
- src/app/components/buttons/MySecondary.tsx
- src/app/components/buttons/MyTertiary.tsx
1. update ButtonDisplay component to include the new changes of button component
> Update ButtonDisplay component

- src/app/api/auth/confirmResetPassword/route.ts
- src/app/api/auth/resendSignUpCode/route.ts
- src/app/api/auth/resetPassword/route.ts
- src/app/api/auth/signUp/route.ts
- src/app/api/user/route.ts
- src/app/utilities/auth/constants.ts
- src/app/utilities/auth/responses.ts
- src/app/utilities/auth/updateUser.ts
- src/app/utilities/responses.ts
- src/app/utilities/validation/assertUserData.ts
- Slightly better handling of authentication and database related errors
- Changing DOB format to string from number for filtering purpose
> Auth error handler tweak

- package-lock.json
- package.json
- src/app/components/auth/AuthInitForgotPassword.tsx
- src/app/components/auth/AuthInitSignUp.tsx
- src/app/components/auth/AuthVerifyForm.tsx
- src/app/components/auth/Login.tsx
- src/app/components/navbar/UserOutlet.tsx
- src/app/components/toaster/ToasterWrapper.tsx
- src/app/components/toaster/index.ts
- src/app/components/toaster/toaster.module.css
- src/app/utilities/common.ts
- src/app/utilities/toaster/constants.ts
- Removing `react-hot-toast` library
- Creating a custom toast component
- `success`, `error` and `info` function to trigger different type of toasts
- Toast dismissal after a specified duration
> New Toast Component

- src/app/api/course/details/GET.ts
- src/app/api/course/details/route.ts
- src/app/api/db/course/details/GET.ts
- src/app/api/db/course/details/POST.ts
- src/app/api/db/course/details/PUT.ts
- src/app/api/db/course/details/route.ts
- src/app/interfaces/Course.ts
- src/app/utilities/db/constants.ts
- src/app/utilities/db/course/createCourseDetailsTable.ts
- src/app/utilities/db/course/describeCourseDetailsTable.ts
- src/app/utilities/db/course/insertCourseDetails.ts
- src/app/utilities/validation/assertCourseDetailsData.ts
- src/app/utilities/validation/assertCourseDetailsWithoutIdData.ts
- src/app/utilities/validation/assertCourseWithoutIdData.ts
- Table creation by allowed admin users through endpoints
- Endpoint to get a specific course details
> Course Details Table

- src/app/components/auth/AuthFinishForgotPassword.tsx
- src/app/components/auth/AuthInitForgotPassword.tsx
- src/app/components/auth/AuthInitSignUp.tsx
- src/app/components/auth/AuthResendOTPBtn.tsx
- src/app/components/profile/ProfileBody.tsx
- src/app/components/profile/ProfileBodyHeader.tsx
- src/app/components/profile/ProfileChallengeSection/index.tsx
- src/app/components/profile/ProfileGoalSection/index.tsx
- src/app/components/profile/ProfileInfoSection/index.tsx
- src/app/components/profile/ProfilePreferenceSection/index.tsx
- src/app/components/profile/ProfileStrategySection/index.tsx
- src/app/components/profile/profileBody.module.css
- src/app/interfaces/APIError.ts
- src/app/interfaces/Profile.ts
- src/app/utilities/auth/constants.ts
- src/app/utilities/common.ts
- src/app/utilities/profile/ProfileProvider.tsx
- src/app/utilities/profile/processProfileFormData.ts
- src/app/utilities/profile/saveUserProfile.ts
**Merge #104 First**
Saving profile form input data to database.
> Profile - Save

- src/app/components/profile/ProfileAttributes/ProfileAttribute.tsx
- src/app/components/profile/ProfileAttributes/ProfileEmptyDescription.tsx
- src/app/components/profile/ProfileAttributes/index.tsx
- src/app/components/profile/ProfileAttributes/profileAttribute.module.css
- src/app/components/profile/ProfileBody.tsx
- src/app/components/profile/ProfileBodyHeader.tsx
- src/app/components/profile/ProfileChallengeSection/Form.tsx
- src/app/components/profile/ProfileChallengeSection/index.tsx
- src/app/components/profile/ProfileGoalSection/Form.tsx
- src/app/components/profile/ProfileGoalSection/index.tsx
- src/app/components/profile/ProfilePreferenceSection/Form.tsx
- src/app/components/profile/ProfilePreferenceSection/index.tsx
- src/app/components/profile/ProfileStrategySection/Form.tsx
- src/app/components/profile/ProfileStrategySection/index.tsx
- src/app/components/profile/profileBodyHeader.module.css
- src/app/components/profile/profileCard.module.css
- src/app/hooks/usePrevious.ts
- src/app/hooks/useUpdatedValue.ts
- src/app/interfaces/User.ts
- src/app/utilities/auth/constants.ts
- src/app/utilities/profile/ProfileProvider.tsx
- src/app/utilities/profile/constants.ts
- src/app/utilities/profile/getProfileSectionData.ts
**Merge #105 First**
Edit/Read-only mode of profile interface.
> Profile - Mode

- src/app/components/buttons/ActionButton.tsx
- src/app/components/dialog/dialog.module.css
- src/app/components/dialog/index.tsx
- src/app/components/images/Add.tsx
- src/app/components/images/ArrowDown.tsx
- src/app/components/profile/ProfileAttributes/index.tsx
- src/app/components/profile/ProfileAttributes/profileAttribute.module.css
- src/app/components/profile/ProfileBody.tsx
- src/app/components/profile/ProfileCard.tsx
- src/app/components/profile/ProfileChallengeSection/Form.tsx
- src/app/components/profile/ProfileChallengeSection/index.tsx
- src/app/components/profile/ProfileFormFooter.tsx
- src/app/components/profile/ProfileGoalSection/Form.tsx
- src/app/components/profile/ProfileGoalSection/index.tsx
- src/app/components/profile/ProfilePreferenceSection/Form.tsx
- src/app/components/profile/ProfilePreferenceSection/index.tsx
- src/app/components/profile/ProfileStrategySection/Form.tsx
- src/app/components/profile/ProfileStrategySection/index.tsx
- src/app/components/profile/profileBody.module.css
- src/app/components/profile/profileCard.module.css
- src/app/components/profile/profileFormFooter.module.css
- src/app/components/profile/profileRightSidebar.module.css
- src/app/hooks/useIsProfileSectionEmpty.ts
- src/app/interfaces/Profile.ts
- src/app/utilities/profile/ProfileProvider.tsx
- src/app/utilities/profile/constants.ts
**Merge #106 First**
Popup form of unedited/untouched profile sections.
> Profile - Popup Form

- src/app/components/LearnMore/learnMore.module.css
- src/app/components/auth/AuthFinishForgotPassword.tsx
- src/app/components/auth/AuthInitForgotPassword.tsx
- src/app/components/auth/AuthInitSignUp.tsx
- src/app/components/auth/AuthVerifyForm.tsx
- src/app/components/auth/Login.tsx
- src/app/components/auth/auth.module.css
- src/app/components/buttons/button.module.css
- src/app/components/formElements/Form.tsx
- src/app/components/formElements/TextArea/textarea.module.css
- src/app/components/formElements/TextBox/textBox.module.css
- src/app/components/formElements/form.module.css
- src/app/components/profile/ProfileAttributes/profileAttribute.module.css
- src/app/components/profile/ProfileBodyHeader.tsx
- src/app/components/profile/ProfileChallengeSection/Form.tsx
- src/app/components/profile/ProfileFormFooter.tsx
- src/app/components/profile/ProfileGoalSection/Form.tsx
- src/app/components/profile/ProfilePreferenceSection/Form.tsx
- src/app/components/profile/ProfileStrategySection/Form.tsx
- src/app/components/profile/profileBody.module.css
- src/app/components/profile/profileBodyHeader.module.css
- src/app/components/profile/profileCard.module.css
- src/app/components/profile/profileContainer.module.css
- src/app/components/profile/profileFormFooter.module.css
- src/app/components/profile/profileRightSidebar.module.css
- src/app/globals.css
- src/app/utilities/profile/ProfileProvider.tsx
**Merge #107 First**
- Button style refurbishing to better equip to handle responsive edge cases
- Form elements: replacing per element padding/margin with container gap
- Decreasing spacing of overall profile interface
> Cosmetic changes

- src/app/components/buttons/button.module.css
- src/app/components/navbar/Navbar.tsx
- src/app/components/navbar/UserOutlet.tsx
- src/app/components/navbar/navbar.module.css
- src/app/globals.css
> Update navbar UI

- src/app/api/course/createCheckoutUrl/route.ts
> Add tax section

- src/app/api/course/createCheckoutUrl/route.ts
> Create tax section

- src/app/api/course/createCheckoutUrl/route.ts
> Add config for invoice

- src/app/components/course/CourseEnrolPrompt/CourseBanner.tsx
- src/app/components/course/CourseEnrolPrompt/CourseEnrolPopup.tsx
- src/app/components/course/CourseEnrolPrompt/courseEnrolPrompt.module.css
- src/app/components/course/CourseEnrolPrompt/index.tsx
- src/app/utilities/course/constants.ts
- Using `sessionStorage` to enforce popup on every new session
- Enlarging 'Enrol' button, placing it beside the course title
> Course enrolment component update

- src/app/api/auth/signUp/route.ts
- src/app/api/db/course/GET.ts
- src/app/api/db/course/POST.ts
- src/app/api/db/course/PUT.ts
- src/app/api/db/course/details/GET.ts
- src/app/api/db/course/details/PUT.ts
- src/app/api/user/route.ts
- src/app/components/auth/AuthInitSignUp.tsx
- src/app/interfaces/User.ts
- src/app/utilities/auth/constants.ts
- src/app/utilities/auth/createUser.ts
- src/app/utilities/auth/isAuthenticated.ts
- src/app/utilities/auth/nextAuthOptions.ts
- src/app/utilities/common.ts
- src/app/utilities/stripe/constants.ts
Alter createUser function to insert data eg email, firstName, lastName, dob and subscribed into dynamoDB.
> Extend user creation process

- src/app/components/aboutFounders/founders.module.css
> Fix founders mobile view

- src/app/components/banner/banner.module.css
- src/app/components/teacherSection/Teacher.tsx
- src/app/page.tsx
> Restore banner

- src/app/articles/page.tsx
- src/app/blogs/page.tsx
- src/app/components/textHeavyArticle/TextHeavyArticle.tsx
- src/app/components/textHeavyBlog/textHeavyBlog.tsx
Links in articles and blogs now open in a new tab.
> Links in a new tab

- src/app/components/article/card.tsx
- src/app/components/blog/BlogCardList.tsx
Articles and blogs cards now appear in descending order on their respective pages.
> Articles and blogs cards

- src/app/components/banner/HomeBanner.tsx
changed text in the home banner
> changed text in the home banner

- src/app/components/partnerSection/Partner.tsx
- src/app/page.tsx
Move around partner and change wording to supported
> Move around partner and change wording to supported
